### ISSUE TITLE
Issue with the monthly repeat shortcode...

### ISSUE THREAD

**Issue by imagemakerswi** [theukedge/shortcodes-to-show-or-hide-content#15]
Hi all,

I'm using this to show/hide 4 sections depending on days of the month. (for example show A on days 1-8, but not sections B, C or D. Show B on days 9-15 but not sections A, C or D etc etc)

I'm using the time-restrict-repeat shortcode. I'm noticing an issue with our fourth & last section. The "time-restrict-repeat-4" shortcode. It doesn't seem to matter what content I put in there, it isn't getting read properly. Instead of the content being hidden right now (as it should be since we only on day 11 of the month) it is actually being shown, You can see a live example here: http://www.kingswayhomes.com/testing/. I will also attach a ZIP to this post that shows my working HTML code.

PS - I have done a bunch of troubleshooting on this. I copied/pasted the code from section 4 into the time-restrict-repeat-3" shortcode & it worked perfectly fine. This is why I'm stumped. It was working fine a few months back when we implemented it.

Thanks for any help you can provide!
-CT

[salesppl-rotation-code.html.zip](https://github.com/theukedge/shortcodes-to-show-or-hide-content/files/85948/salesppl-rotation-code.html.zip)

**Comment by theukedge** [comment]
Hey CT,

OK, I've taken a look at what you sent over and this is just a misunderstanding of how the shortcode works. The multiple shortcodes (`[time-restrict-repeat-2]` and `[time-restrict-repeat-3]`)are not for use with subsequent items that have differing conditions, but rather for nesting the shortcodes if needed. e.g. (`[time-restrict-repeat][time-restrict-repeat-2]Content[/time-restrict-repeat-2][/time-restrict-repeat]`). That's why there are only 3 versions of it, because it is unlikely that you would need to nest more than 3 shortcodes and for the same reason, this why your `[time-restrict-repeat-4]` shortcode isn't working: it doesn't exist.

Just use [time-restrict-repeat] throughout unless you need to nest a shortcode.

**Comment by imagemakerswi** [comment]
Dave - thanks for that!

Another question. We are using the same code on two different sites (within the same WP install). We have the same code on both sites. One is showing the sidebar correctly while the other one isn't.

Showing correct on site no1: http://www.kingswayhomes.com/barton-open-model/
Not showing correct on site no2: http://www.kingswayhomes.com/chapel-hill/cherbourg/.

**Comment by theukedge** [comment]
My bet is that it's to do with one of the sites not executing shortcodes in
the sidebar widgets. See this article for guidance on how to remedy it:
https://digwp.com/2010/03/shortcodes-in-widgets/

Dave Clements
WordPress developer

dave@theukedge.com
Google Hangouts: dave@davidclements.me

[image: The UK Edge Logo] <http://www.theukedge.com/>

**Comment by imagemakerswi** [comment]
That didn't work :( I'm at a loss.

Both sites are using the same exact code in Widgets. Seems so strange that it works on one but not the other. Also, both sites are using the same exact WP theme.

**Comment by imagemakerswi** [comment]
Hold on - I'm an idiot. I think I just figured out. I'll update you shortly.

**Comment by imagemakerswi** [comment]
Yes, fixed it. We are all good - thanks for the help today!
