### ISSUE TITLE
weekly / day by day

### ISSUE THREAD

**Issue by robertdeniro** [theukedge/shortcodes-to-show-or-hide-content#16]
hi, thanks for your great work!

i'm working with the weekly mode like this

[time-restrict-repeat type="weekly" onday="Sunday" offday="Monday"]
Hello
[/time-restrict-repeat] 
[time-restrict-repeat type="weekly" onday="Monday" offday="Tuesday"]
Hello again
[/time-restrict-repeat] 
[time-restrict-repeat type="weekly" onday="Tuesday" offday="Wednesday"]
Hello again
[/time-restrict-repeat] 

and so on... till onday="Saturday" offday="Sunday"

but recently there will be shown the first and the last entry. is this a bug? or what is wrong with that?
thanks for your help!

**Comment by theukedge** [comment]
Hi Robert,

I'm just now getting a chance to look at this. I think it's simply because your syntax is incorrect. I'm guessing that you want these things to only show up for one day. The way you've written it, each item will show up for two days (e.g. 00:00:00 on Sunday to 23:59:59 on Monday), so there will always be two items showing. If you want just one item at a time, set the `onday` and `offday` to the same day and you'll be set.

Let me know if that isn't the case.
