### ISSUE TITLE
"else" not acting as expected

### ISSUE THREAD

**Issue by hexfield** [theukedge/shortcodes-to-show-or-hide-content#24]
Hi, I'm using your great show/hide content plugin but I can't get the "else" parameter to work. I have a css class for product buttons, and on certain dates I want to add a note that the product is 25% off. outside of that timeframe, I want to display the regular price of $24.99 instead. Here's my code:

`<a class="buybutton" href="link">product name[time-restrict on="11/25/2016" off="11/29/2016" else="$24.99"] <span class="circleCall">25%<br>Off</span>[/time-restrict]</a>`

The 25% off text is displaying correctly within the timeframe, but the else text of $24.99 never appears.

**Comment by theukedge** [comment]
I think this is because the version in the WordPress repository is at 2.4. The readme includes details about the else message, even though that was added in 2.5, which evidently has not been pushed for release.

SO, if you replace /plugins/shortcodes-to-show-or-hide-content/includes/shortcodes.php with [this](https://github.com/theukedge/shortcodes-to-show-or-hide-content/blob/9940151529d9fb2fc6e3cfeafb9e37b62ac403bc/includes/shortcodes.php), it should work.

**Comment by hexfield** [comment]
Perfect, that fixed it! Thanks so much!

--R


Ryan DiGiorgi
hellofromthemagictavern.com

**Comment by theukedge** [comment]
Thanks for reporting back. I'm glad to hear it.
