### ISSUE TITLE
The blank between the head and the post

### ISSUE THREAD

**Issue by sw1115** [theukedge/shortcodes-to-show-or-hide-content#40]
[http://michaelczinkota.com/daily-iconoclast/(url)

hello guys!
i just have a problem which is that there is always a big blank space between heading and post on my website.

How can I eliminate the blank?

any assistance will be greatly appreciated!!

best,
shiying
![2019-01-17 18 08 26](https://user-images.githubusercontent.com/46799426/51354803-d69a0700-1a82-11e9-8040-1ee32e4bcdc6.png)

**Comment by sw1115** [comment]
http://michaelczinkota.com/daily-iconoclast/
here is the link

**Comment by theukedge** [comment]
You've added a paragraph break between the shortcode and the HTML. So you probably have something like this:

`[time-restrict-repeat...]

December 28, 2018
IMG
[/time-restrict-repeat]`

whereas you need something more like:

`[time-restrict-repeat...]December 28, 2018
IMG
[/time-restrict-repeat]`

where there's no space between the end of the shortcode and the content it's supposed to be hiding.

**Comment by sw1115** [comment]
![2019-01-17 18 31 13](https://user-images.githubusercontent.com/46799426/51355754-0d255100-1a86-11e9-875c-ed9704d289df.png)
Thanks a lot for your prompt reply!!!
but after i got like this there is still a large blank space existed.

http://michaelczinkota.com/daily-iconoclast/

**Comment by theukedge** [comment]
![image](https://user-images.githubusercontent.com/3171242/51355909-692fab80-1a6d-11e9-917e-990aaa1d7fb8.png)

Something is creating loads of empty paragraphs. Do you have multiple conditions? My guess is you have each condition in its own paragraph, so it creates a paragraph, but then the shortcode is all that's in that paragraph, and since all the content is hidden because the conditions of the shortcode are satisfied, it just leaves behind an empty paragraph. Sequential conditions also need to butt up against one another. e.g.:

`[time-restrict-repeat type="annually" onmonth="January" offmonth="January" ondate="17" offdate="17"]This is the content for the 17th[/time-restrict-repeat][time-restrict-repeat type="annually" onmonth="January" offmonth="January" ondate="18" offdate="18"]This is the content for the 18th[/time-restrict-repeat]`

Notice that there is no gap and no new paragraph between `[/time-restrict-repeat]` and the next instance of `[time-restrict-repeat...]`. It will likely be easier to edit this in HTML mode than visually to ensure you put the shortcodes as they ought to be.

**Comment by sw1115** [comment]
Thank you sooooo much!!!!!!

**Comment by theukedge** [comment]
My pleasure :)
