### ISSUE TITLE
Not working with text

### ISSUE THREAD

**Issue by amolmandar** [theukedge/shortcodes-to-show-or-hide-content#6]
[time-restrict-repeat type="weekly" onday="Monday" offday="Friday"]<span style="background-color:white;color:red">Raju is good boy</span>[/time-restrict-repeat]

This shortcode works well with Post or Page but fails with Text widget! Why is it so?

**Comment by theukedge** [comment]
My guess is that if it's working normally in posts and pages, then the issue is not the plugin itself, but rather that your widgets are not executing shortcodes. You can overcome this by putting [this simple snippet](http://digwp.com/2010/03/shortcodes-in-widgets/) in your [functionality plugin](http://www.doitwithwp.com/putting-things-where-they-belong/)
